name: Lint

on: [push]

jobs:
  build:
    name: eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: actions/cache@v3 
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-

      - uses: actions/npm@v3
        with:
          cmd: install

      - run: npm run eslint:github-action 
