name: Lint
on:
  push:
    branches:
      - main 
  pull_request: 
    branches: 
      - main

jobs:
  build:
    name: eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: eslint install
        run: npm install -g eslint 
      - name: Install Dependencies
        run: npm install
      - name: Run ESLint
        run: eslint ./
