name: Deploy Backend

on:
  push:
    branches:
      - main # Adjust the branch name as needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Variables
        run: |
          echo "CURRENT_DATETIME=$(date +%Y-%m-%d_%H-%M-%S)" >> $GITHUB_ENV
          echo "DIR_NAME=${HOME}/${CURRENT_DATETIME}" >> $GITHUB_ENV
          echo "PROJECT_NAME=transaction" >> $GITHUB_ENV
          echo "PORT=30005" >> $GITHUB_ENV

      - name: Zip Contents
        run: zip -r deployment.zip ./ --exclude=".git/" --exclude="app/config/" --exclude=".env"

      - name: Move Old  Backend
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_ADDRESS }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
             mv /home/ubuntu/github/${{ env.PROJECT_NAME }}-backend /home/ubuntu/github/bus/${{ env.PROJECT_NAME }}-backend-${{ env.CURRENT_DATETIME }} || true
             rm -rf /home/ubuntu/github/bus/${{ env.PROJECT_NAME }}-backend-${{ env.CURRENT_DATETIME }}/node_modules || true

      - name: Copy to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_ADDRESS }} # Add your server host here
          username: ${{ secrets.SERVER_USERNAME }} # Add your server username here
          key: ${{ secrets.SSH_PRIVATE_KEY }} # Add your .pem key content here
          source: "deployment.zip"
          target: "${HOME}/github/${{ env.PROJECT_NAME }}-backend/"

      - name: RUN COMMAND AT LAST
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_ADDRESS }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
             bash /home/ubuntu/bashes/deploy_backend.sh ${{ env.PROJECT_NAME }} ${{ env.PORT }}